myName=input("What is your name?")
myAge=input("How old are you?")
print("Gee, that's REALLY OLD")
replit=input("Do you like Replit?")
print("OF COURSE YOU DO!")
print()
print("So, you are")
print(myName)
print("and are the ripe old age of")
print(myAge)
print("and clearly think that Replit is")
print(replit)
myLunch=input("What are you having for lunch? ")
print("Hmm,it sounds like you really should just order")
print("myLunch")
print("as soon as possible!")
print()
print("Getting to know you!")
print()
myName=input("What is your name?")
print("Nice to meet you"+ myName)
myFood=input("What is your favourite food?")
print("I like"+ myFood +"too!")
myMusic=input("What is your favourite music?")
print("I like"+ myMusic +"too!")
myLocation=input("Where do you live?")
print("I live in" + myLocation +"too!)")
